const { connectLambda, getStore } = require('@netlify/blobs');
const crypto = require('crypto');
const STORE='google-form-cache';

exports.handler=async(event)=>{if(event.httpMethod!=='POST')return reply(405,{error:'Metode tidak diizinkan.'});try{connectLambda(event);const body=JSON.parse(event.body||'{}');const forcedTermination=body.forcedTermination===true;const formId=decodeId(body.id);const cached=await getStore(STORE).get(`form-${formId}`,{type:'json'});if(!cached)return reply(404,{error:'Data ujian tidak ditemukan. Minta guru melakukan Generate Ulang.'});const answers=body.answers&&typeof body.answers==='object'?body.answers:{};const params=new URLSearchParams();let missing=0;
  for(const q of cached.questions){if(q.type==='UNSUPPORTED')continue;const value=answers[q.entryId];const values=Array.isArray(value)?value:[value];const clean=values.filter(v=>typeof v==='string'&&v.trim()!=='').map(v=>v.trim());if(q.required&&!clean.length)missing++;for(const v of clean){if((q.type==='RADIO'||q.type==='DROPDOWN'||q.type==='CHECKBOX')&&!q.options.includes(v))continue;params.append(q.entryId,v)}}
  if(missing&&!forcedTermination)return reply(400,{error:`Masih ada ${missing} pertanyaan wajib yang belum dijawab.`});params.set('fvv','1');params.set('pageHistory','0');if(forcedTermination)params.set('submissionTimestamp',String(Date.now()));const target=`https://docs.google.com/forms/d/e/${formId}/formResponse`;const r=await fetch(target,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'Mozilla/5.0 (compatible; TKAFormRenderer/2.0)'},body:params.toString(),redirect:'manual'});const text=await r.text().catch(()=>'');if(/no longer accepting responses|tidak lagi menerima respons|formulir telah ditutup/i.test(text))throw userError('Google Form sudah ditutup dan tidak menerima respons.',409);if(!(r.status===200||(r.status>=300&&r.status<400)))throw userError(`Google menolak pengiriman jawaban (HTTP ${r.status}).`,502);const submittedAt=new Date().toISOString(),receiptCode=createReceipt(submittedAt);return reply(200,{success:true,forcedTermination,submittedAt,receiptCode,message:'Jawaban Anda telah berhasil dikumpulkan.'});
}catch(err){console.error('submit-form:',err);return reply(err.status||500,{error:err.publicMessage||'Jawaban gagal dikirim. Periksa koneksi lalu coba lagi.'})}};
function decodeId(v){if(typeof v!=='string')throw userError('ID ujian tidak valid.');const id=Buffer.from(v,'base64url').toString('utf8');if(!/^[a-zA-Z0-9_-]{20,}$/.test(id))throw userError('ID ujian tidak valid.');return id}function userError(message,status=400){const e=new Error(message);e.publicMessage=message;e.status=status;return e}function reply(statusCode,body){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function createReceipt(iso){const day=iso.slice(0,10).replace(/-/g,''),random=crypto.randomBytes(4).toString('hex').toUpperCase();return `TKA-${day}-${random}`}
exports._test={createReceipt};
