const crypto=require('crypto');
const formTools=require('./fetch-form')._test;

exports.handler=async(event)=>{if(event.httpMethod!=='POST')return reply(405,{error:'Metode tidak diizinkan.'});try{const body=JSON.parse(event.body||'{}'),forcedTermination=body.forcedTermination===true,payload=formTools.decodeExamId(body.id),html=await formTools.fetchHtml(formTools.canonicalViewUrl(payload.formId)),form=formTools.parseGoogleForm(html,payload.formId),metadata=form.submitMetadata;if(!metadata?.fbzx)throw userError('Metadata pengiriman Google Form tidak dapat dibaca. Silakan coba lagi.',502);const answers=body.answers&&typeof body.answers==='object'?body.answers:{},params=new URLSearchParams();let missing=0;
  for(const q of form.questions){if(q.type==='UNSUPPORTED'||q.type==='FILE_UPLOAD')continue;const value=answers[q.entryId],values=Array.isArray(value)?value:[value],clean=values.filter(v=>typeof v==='string'&&v.trim()!=='').map(v=>v.trim());if(q.required&&!clean.length)missing++;for(const v of clean){if((q.type==='RADIO'||q.type==='DROPDOWN'||q.type==='CHECKBOX')&&!q.options.includes(v))continue;params.append(q.entryId,v)}}
  if(missing&&!forcedTermination)return reply(400,{error:`Masih ada ${missing} pertanyaan wajib yang belum dijawab.`});params.set('fvv',metadata.fvv||'1');params.set('partialResponse',JSON.stringify([null,null,metadata.fbzx]));params.set('pageHistory',metadata.pageHistory||'0');params.set('fbzx',metadata.fbzx);params.set('submissionTimestamp',metadata.submissionTimestamp||'-1');const target=`https://docs.google.com/forms/d/e/${payload.formId}/formResponse`,r=await fetch(target,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'Mozilla/5.0 (compatible; TKAFormRenderer/2.1)'},body:params.toString(),redirect:'manual'}),text=await r.text().catch(()=>'');if(/no longer accepting responses|tidak lagi menerima respons|formulir telah ditutup/i.test(text))throw userError('Google Form sudah ditutup dan tidak menerima respons.',409);if(!(r.status===200||(r.status>=300&&r.status<400))){console.error('Google formResponse rejected',{status:r.status,pageHistory:metadata.pageHistory,hasFbzx:Boolean(metadata.fbzx)});throw userError(`Google menolak pengiriman jawaban (HTTP ${r.status}).`,502)}const submittedAt=new Date().toISOString(),receiptCode=createReceipt(submittedAt);return reply(200,{success:true,forcedTermination,submittedAt,receiptCode,message:'Jawaban Anda telah berhasil dikumpulkan.'})
}catch(err){console.error('submit-form:',err);return reply(err.status||500,{error:err.publicMessage||'Jawaban gagal dikirim. Periksa koneksi lalu coba lagi.'})}};
function userError(message,status=400){const e=new Error(message);e.publicMessage=message;e.status=status;return e}function reply(statusCode,body){return{statusCode,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'},body:JSON.stringify(body)}}
function createReceipt(iso){const day=iso.slice(0,10).replace(/-/g,''),random=crypto.randomBytes(4).toString('hex').toUpperCase();return`TKA-${day}-${random}`}
exports._test={createReceipt};
